version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing Terraform...
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo Logging in to AWS
      - terraform --version
      - cd terraform
      - terraform init 
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
